import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import Card from "../components/card/card";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="michal" />
      <Banner
        title="Clifford red"
        subtitle="a very cute dog"
        imgUrl="/static/210629.jpg"
      />

      <Card imgUrl="/static/210629.jpg" size="large" />
      <Card  size="medium" />
      <Card imgUrl="/static/210629.jpg" size="small" />
    </div>
  );
};

export default Home;
